# Generated by Django 3.2.5 on 2021-09-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='classes',
        ),
        migrations.AddField(
            model_name='classes',
            name='course',
            field=models.ManyToManyField(to='education.Course'),
        ),
        migrations.AddField(
            model_name='classes',
            name='student',
            field=models.ManyToManyField(to='education.Student'),
        ),
        migrations.AddField(
            model_name='classes',
            name='teacher',
            field=models.ManyToManyField(to='education.Teacher'),
        ),
    ]
