# Generated by Django 3.2.6 on 2021-08-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='students',
            new_name='student',
        ),
    ]
