# Generated by Django 3.2.6 on 2021-08-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_rename_students_classes_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='course',
            field=models.ManyToManyField(to='education.Course'),
        ),
    ]
